### ISSUE TITLE
Alternative installation method

### ISSUE THREAD

**Issue by Reggino** [webpack/json-loader#12]
Thank you for this!

Since node 5 it is possible to just require .json files (see discussion e.g. https://github.com/webpack/webpack/issues/184 and https://github.com/nodejs/node-v0.x-archive/blob/master/lib/module.js#L485 )

To reflect that, it would be nice if the README.md could point out that the same syntax (`require('sample.json')`) can be used, using this loader by adding

```
  module: {
    loaders: [
    {
      test: /\.json$/,
      loader: 'json'
    }]
  }
```
to your Webpack configuration file. It took me a while to figure that out while `require`-ing node 5 modules.

**Comment by IngwiePhoenix** [comment]
Small correction here:

Node’s native JSON loading was possible even within 0.10.x releases.

**Comment by SpaceK33z** [comment]
PR welcome. Note that this is also somewhat related to #7.

**Comment by SpaceK33z** [comment]
Closing since to use json in webpack, you still need `json-loader`.
