### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token m

### ISSUE THREAD

**Issue by cheshire137** [webpack/json-loader#13]
This is what I'm getting:

```
ERROR in ./src/components/config.json
Module build failed: SyntaxError: Unexpected token m
    at Object.parse (native)
    at Object.module.exports (/Users/me/my-project/node_modules/json-loader/index.js:7:48)
 @ ./src/components/Main.js 28:13-37
```

The relevant JSON file I'm trying to load:

```json
{
  "redirectUri": "http://localhost:8000/webpack-dev-server/"
}
```

I'm requiring it via `var Config = require('./config.json');`. I had the same error when I did `require('json!./config.json')`.

I have this in my list of `loaders`:

```javascript
{
  test: /\.json$/,
  loader: 'json-loader!json-loader'
}
```

I got the same error when I moved the loader to the `preLoaders` section.

This is the version I'm using: `"json-loader": "^0.5.4"`.

**Comment by cheshire137** [comment]
Looks like a duplicate of #10 that may have been fixed by #11 but 11 got closed instead of merged.

**Comment by cheshire137** [comment]
I ended up using [raw-loader](https://github.com/webpack/raw-loader) and loading my file like this: `var Config = JSON.parse(require('components/config.json'));` The following is in my `loaders` section:

```json
{
  test: /\.json$/,
  loader: 'raw-loader'
}
```

**Comment by startupthekid** [comment]
@cheshire137 I ran into the same issue today and for me at least, it was because I wasn't escaping double quotes like 
```
{
    "text": "This is some example \"text\""
}
```

I also ran into an issue with using ES6 `import` syntax and [eslint-import-plugin](https://www.npmjs.com/package/eslint-plugin-import), it couldn't find the default export for josn but if you use `require` you should be a-ok.

**Comment by vinayrajp** [comment]
I ran into the same issue as well with json-loader.
@cheshire137 I also ran into this issue with raw-loader. 
<code> var Config = require('components/config.json')); </code>
would return module.exports = { json data } and when that was passed to JSON.parse, I got the same Unexpected token m (since the file starts with m). Not sure why just the data within the file was not returned with raw-loader.

**Comment by mindmelting** [comment]
Can confirm #11 fixes this issue...

**Comment by nhll** [comment]
I got the same error. Any news on this issue?

Can also confirm #11 fixes this, why didn't it get merged?

**Comment by salsa2k** [comment]
I have the same issue

**Comment by Martskin** [comment]
> Can confirm #11 fixes this issue...

Yeah, #11 fixes it for me too.

**Comment by sokra** [comment]
This issue occurs when applying the json-loader twice. i. e. by using configuration + `require("json!`. That's wrong. #11 is only a workaround, but not the solution. Fix your configuration resp. code.

**Comment by Martskin** [comment]
Thanks @sokra ! Removing `require("json!` did the trick.

**Comment by Shinobi881** [comment]
In case anyone is still having an issue with this loader, I got it to work by adding and extra `!` to my `import/require` statement.

Ex: `import Data from '!json!../../data';`
And the loader: `{ test: /\.json$/, loaders: ['json-loader'] }`

**Comment by mattdell** [comment]
I fixed this issue by moving `json-loader` from loaders into preLoaders.

**Comment by demidovVladimirAuto1** [comment]
When #11 will be merged to not checkout git repo?

**Comment by chrisrittelmeyer** [comment]
I think I'm having the same problem, but not sure what's causing it. My loader config is:
```
{
   test: /\.json$/,
   loader: 'json'
}
```
and then later I attempt to dynamically load some json files with:
`const req = require.context('../locales', true, /\.json.*$/)`
but get the "unexpected token" error. I tried moving it to `preLoaders`, to no avail. Finally, I tried commenting out the json loader config altogether, and voila. For some reason it works? Any idea why?

**Comment by gibo** [comment]
+1

**Comment by sokra** [comment]
https://github.com/webpack/json-loader/issues/13#issuecomment-188480384

**Comment by AlastairTaft** [comment]
Still can't get it to work despite trying all of the above recommendations.

**Comment by chmursonss** [comment]
Switching to fork (compact-json-loader)[#https://github.com/also/compact-json-loader] helps :)

**Comment by MouseZero** [comment]
I had to remove the "json!" and then it worked.
