### ISSUE TITLE
Is this the correct package to use for React component to read mongo json from URL?

### ISSUE THREAD

**Issue by scheung38** [webpack/json-loader#24]
I want to read mongo from URL in a React component: 

`$ mongo ec2-XX-XX-X-XXX.us-west-2.compute.amazonaws.com:27017
`

is this the correct package for this job? If not could you point out the relevant package for doing so programmatically?

**Comment by SpaceK33z** [comment]
No, you should do an XHR request to fetch the json. You can use [fetch](https://davidwalsh.name/fetch) for example.
