### ISSUE TITLE
Add support for webpack2

### ISSUE THREAD

**Issue by monolithed** [webpack/json-loader#33]
```
(node:38259) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Module '/node_modules/json-loader/index.js' is not a loader (must have normal or pitch function)
```

webpack@^2.1.0-beta.25

**Comment by SpaceK33z** [comment]
I'm using json-loader with webpack v2 and it's working for me. Do you use `extract-text-webpack-plugin`, and if so, what version?

**Comment by monolithed** [comment]
> Do you use extract-text-webpack-plugin, and if so, what version?

Yep,`extract-text-webpack-plugin@^2.0.0-beta.4`

**Comment by waltfy** [comment]
@monolithed have you found a work around to this yet? Let me know if I can help in any way!

**Comment by waltfy** [comment]
@SpaceK33z seems like removing the requirement for `extract-text-webpack-plugin` seems to resolve the issues for `json-loader` — do you have more context?

**Comment by SpaceK33z** [comment]
@waltfy it might be related to https://github.com/webpack/extract-text-webpack-plugin/issues/265, but not sure.

**Comment by monolithed** [comment]
@SpaceK33z
> I'm using json-loader with webpack v2 and it's working for me.

Have you tried to delete your `node_modules` before?

@waltfy
> have you found a workaround for this yet? Let me know if I can help in any way!

 I rolled to a previous version 😄

**Comment by SpaceK33z** [comment]
Jep, just tried it again. What version did you rollback to? And does the problem disappear if you don't use extract-text-webpack-plugin?

**Comment by monolithed** [comment]
@SpaceK33z, I meant `"webpack": "^1.13.2"`, `"json-loader": "0.5.4"` :)

**Comment by SpaceK33z** [comment]
Okay, but could you checkout if it happens without extract-text-webpack-plugin? This is crucial for me to know because if so, it is most probably an issue with extract-text-webpack-plugin.

**Comment by monolithed** [comment]
> Okay, but could you checkout if it happens without extract-text-webpack-plugin?

Alas, I did not keep that state in the history of commits, sorry.

**Comment by SpaceK33z** [comment]
Okay, then I'm going to close this since webpack v2 with json-loader *does* work, but it is some other package (probably extract-text-webpack-plugin since that fixed it for @waltfy) that introduces this bug.

**Comment by waltfy** [comment]
@SpaceK33z @monolithed I think it makes sense to close the issue. I'll post any useful information I find here, it'll maybe help other people. Thanks! 

👍

**Comment by dsebastien** [comment]
I'm getting the following error when loading json files with Webpack 2 and this plugin (which I don't have with Webpack 1.x:

```
[1m[31mERROR in ./src/stark-app-config.json
Module build failed: SyntaxError: Unexpected token m
    at Object.parse (native)
    at Object.module.exports (C:\LocalData\DEV\Workspace\AAH-Stark\node_modules\json-loader\index.js:7:48)
 @ ./src/app/modules/config/module.ts 12:21-62
 @ ./src/app/modules/index.ts
 @ ./src/app/app.ts
 @ ./src/main.ts
 @ multi main[39m[22m
```

Any ideas? I guess the 'm' in error is part of "module.exports" or something like that.

**Comment by SamHH** [comment]
I'm getting the exact same as @dsebastien.

**Comment by crebuh** [comment]
I've got the same error: 

```
Uncaught Error: Module build failed: SyntaxError: Unexpected token m
    at Object.parse (native)
    at Object.module.exports (/home/Projects/app/node_modules/json-loader/index.js:7:48)
```

I'm using node in version 4.6.0

**Comment by SpaceK33z** [comment]
Okay I'll reopen this, but please provide some useful information so we can narrow this down. Try to remove as many plugins / loaders as possible. Especially try if removing `extract-text-webpack-plugin` works.

**Comment by crebuh** [comment]
I changed my webpack.config config a bit and now it is working again. In the webpack.config I'm now using:

    { test: /\.json$/, loader: 'json-loader' }

and in my files instead of importing the files like this before:

      const routesForBreadcrumb = require('json!../../config/routes.json');

I had to remove the json! at the beginning of the path like

      const routesForBreadcrumb = require('../../config/routes.json');

now it is working in node as well as in the browser environment

**Comment by SpaceK33z** [comment]
@crebuh see https://github.com/webpack/webpack/issues/3359 for a plan on how we want to avoid the issue you had from happening again.

Closing this again since you can fix that error with the above fix.

**Comment by dsebastien** [comment]
In my case, I've doubled checked but I didn't specify the "json!" in the require call, so normally I'm only using the loader once...
