### ISSUE TITLE
"See webpack documentation" needs link and explanation

### ISSUE THREAD

**Issue by grrowl** [webpack/json-loader#4]
> Don't forget to polyfill require if you want to use it in node. See webpack documentation.

Since the webpack documentation isn't doing anyone any favours, it would be great if README could link to a relevant page ([target documentation page](http://webpack.github.io/docs/configuration.html#target), [issue discussion about target](https://github.com/webpack/webpack/issues/225)) and explain something like

> When compiling with "node" as a target, require('package.json') will expect the file (package.json, in this case) to be a real, parseable JS file with a `module.exports`. Adding JSON loader will export the parsed JSON as a real object.

**Comment by sseppola** [comment]
Thank you

**Comment by SpaceK33z** [comment]
Good point. A PR is welcome.

**Comment by SpaceK33z** [comment]
Closing since this statement has been removed.
